language: c
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
script: ./configure && make
matrix:
  include:
    - if: branch = master
      os: osx
      compiler: gcc
      script: brew install --HEAD ncrack && brew test ncrack
    - if: branch = master
      os: osx
      compiler: clang
      script: brew install --HEAD ncrack && brew test ncrack
