language: c
rvm: 2.3.3
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
before_script: if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew bundle; fi
script: ./configure && make
matrix:
  include:
    - if: branch = master
      os: osx
      compiler: gcc
      script: brew install --HEAD ncrack && brew test ncrack
    - if: branch = master
      os: osx
      compiler: clang
      script: brew install --HEAD ncrack && brew test ncrack
